name: Bug Report
description: Report a bug or issue
title: "[Bug]: "
labels: ["bug"]
body:
  - type: markdown
    attributes:
      value: |
        Thanks for taking the time to report this bug!

  - type: textarea
    id: description
    attributes:
      label: Describe the bug
      description: A clear description of what the bug is
      placeholder: Tell us what you see
    validations:
      required: true

  - type: textarea
    id: reproduce
    attributes:
      label: Steps to reproduce
      description: How can we reproduce this?
      placeholder: |
        1. Open app
        2. Click on '...'
        3. See error
    validations:
      required: true

  - type: textarea
    id: expected
    attributes:
      label: Expected behavior
      description: What should happen instead?
      placeholder: Describe what you expected
    validations:
      required: true

  - type: textarea
    id: screenshots
    attributes:
      label: Screenshots
      description: If applicable, add screenshots
      placeholder: Drag and drop images here

  - type: input
    id: version
    attributes:
      label: App version
      description: Check in Help → About
      placeholder: "2.0.0"
    validations:
      required: true

  - type: dropdown
    id: display-server
    attributes:
      label: Display server
      description: Which display server are you using?
      options:
        - Wayland
        - X11
        - Not sure
    validations:
      required: true

  - type: input
    id: desktop
    attributes:
      label: Desktop environment / Window manager
      description: Examples - GNOME, KDE, Hyprland, i3, etc.
      placeholder: "Hyprland"
    validations:
      required: true

  - type: input
    id: distro
    attributes:
      label: Linux distribution
      description: Which distro and version?
      placeholder: "Arch Linux"
    validations:
      required: true

  - type: textarea
    id: logs
    attributes:
      label: Logs
      description: |
        Run the app from terminal and paste any error messages
        Location: ~/.config/netflix-linux/logs/
      placeholder: Paste logs here
      render: shell

  - type: textarea
    id: additional
    attributes:
      label: Additional context
      description: Any other info that might help
      placeholder: Add any other context about the problem

  - type: checkboxes
    id: checklist
    attributes:
      label: Checklist
      options:
        - label: I've searched for similar issues
          required: true
        - label: I've tested with the latest version
          required: true
        - label: This is not a Netflix service issue
          required: true