name: Feature Request
description: Suggest a new feature or improvement
title: "[Feature]: "
labels: ["enhancement"]
body:
  - type: markdown
    attributes:
      value: |
        Thanks for suggesting a feature!

  - type: textarea
    id: problem
    attributes:
      label: Problem or use case
      description: What problem does this solve? What are you trying to do?
      placeholder: I'm frustrated when...
    validations:
      required: true

  - type: textarea
    id: solution
    attributes:
      label: Proposed solution
      description: How would you like this to work?
      placeholder: Describe your ideal solution
    validations:
      required: true

  - type: textarea
    id: alternatives
    attributes:
      label: Alternatives considered
      description: Any other approaches you've thought about?
      placeholder: Describe alternatives

  - type: textarea
    id: examples
    attributes:
      label: Examples
      description: Screenshots, mockups, or examples from other apps
      placeholder: Add visual examples if relevant

  - type: dropdown
    id: priority
    attributes:
      label: How important is this to you?
      options:
        - Nice to have
        - Would be useful
        - Really want this
        - Blocking my usage
    validations:
      required: true

  - type: textarea
    id: additional
    attributes:
      label: Additional context
      description: Anything else we should know?
      placeholder: Add any other context

  - type: checkboxes
    id: checklist
    attributes:
      label: Checklist
      options:
        - label: I've searched for similar feature requests
          required: true
        - label: This feature aligns with the project's goals
          required: true
        - label: I'm willing to help implement this if needed
          required: false